workflows:
  android-workflow:
    name: Build Android AAB - Expo
    environment:
      node: 20
      groups:
        - expo_credentials
    scripts:
      - name: Install EAS CLI
        script: |
          npm install -g @expo/eas-cli
          eas --version
      
      - name: Install project dependencies
        script: |
          npm install
      
      - name: Build with EAS
        script: |
          eas build --platform android --non-interactive
    artifacts:
      - build-*.aab