workflows:
  expo-classic-build:
    name: Expo Classic Build Android AAB
    max_build_duration: 120
    instance_type: mac_mini_m2

    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Login Expo
        script: |
          npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
      - name: Build Android AAB
        script: |
          npx expo build:android -t app-bundle
