workflows:
  android-workflow:
    name: Build Android AAB - Expo
    environment:
      node: 20
      groups:
        - expo_credentials
    scripts:
      - name: Install Expo CLI
        script: |
          npm install -g @expo/cli
      
      - name: Login Expo
        script: |
          expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
      
      - name: Install dependencies
        script: |
          npm install
      
      - name: Build Android AAB
        script: |
          expo build:android --type app-bundle --non-interactive
    artifacts:
      - build-*.aab