workflows:
  android-workflow:
    name: Build Android AAB
    environment:
      groups:
        - keystore_credentials
        - expo_credentials
      vars:
        PACKAGE_NAME: "com.maanoelaurias.ctimperioapp"
    scripts:
      - name: Login Expo
        script: |
          expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
      
      - name: Build Android App Bundle (AAB)
        script: |
          flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/release/*.aab